apiVersion: v1
kind: Service
metadata:
  namespace: jitsi
  labels:
    service: web
  name: web
  annotations:
    domainName: littledarling.org.uk
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: ""
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    external-dns.alpha.kubernetes.io/hostname: littledarling.org.uk
spec:
  selector:
    k8s-app: web
  ports:
  - protocol: TCP
    name: http
    port: 80
    targetPort: http
  - protocol: TCP
    name: https
    port: 443
    targetPort: 443
  type: LoadBalancer
